version: "3.5"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # environment:
    #   - REDIS_PASSWORD=cdhhwfjw8jdjs  # Add this line for Redis password
    # command: ["redis-server", "--requirepass", "cdhhwfjw8jdjs"]  # Require Redis password
    networks:
      - elastic
    restart: always

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
      # - ES_JAVA_OPTS=-Xms1g -Xmx1g # Limit heap to 1 GB
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - elastic
    restart: always # Ensures automatic restart

  postgres:
    platform: "linux/amd64"
    image: postgres:latest
    container_name: backend-postgres-production
    environment:
      - POSTGRES_USER=codewithmuh
      - POSTGRES_PASSWORD=382gsjhgds
      - POSTGRES_DB=codewithmuh_database
    ports:
      - "5432:5432"
    olumes:
      - backend-postgres-production:/var/lib/postgresql
    networks:
      - elastic
    restart: always

  backend:
    platform: "linux/amd64"
    image: backend-django:production
    container_name: backend-django-production
    build:
      context: ../
      dockerfile: ./build-process/docker-backend-django/Dockerfile
      args:
        APP_ENVIRONMENT: "Production"
    volumes:
      - ../:/home/codewithmuh-backend
    ports:
      - "8080:8080"
    env_file:
      - ./production.backend.env
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - elastic
    restart: always

  celery:
    platform: "linux/amd64"
    image: backend-django:production
    container_name: backend-django-celery-production
    build:
      context: ../
      dockerfile: ./build-process/docker-backend-django/Dockerfile
      args:
        APP_ENVIRONMENT: "Production"
    volumes:
      - ../:/home/codewithmuh-backend
    # command: celery -A YOUR_APP worker -l info
    ports:
      - "5555:5555"
    env_file:
      - ./production.backend.env
    depends_on:
      - backend
      - redis
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - elastic
    restart: always

volumes:
  backend-postgres-production:
  esdata:

networks:
  elastic:
    driver: bridge
